[package]
name = "view2d"
version = "0.1.0"
edition = "2021"

[dependencies]
asn-engine = { path = "../../asn-engine" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "view2d-bin"
path = "src/main.rs"

