[workspace]
resolver = "2"
members = [
    "sannbox-wgpu",
    "asn-web-release"
#    "asn-image",
#    "asn-core"
]

#exclude = []
#default-members = [
#    "asn-logger",
#    "rs-core",
#    "rs-gfx-core",
#    "rs-gfx-wgpu",
#    "rs-amberskynet"
#]
