[workspace]
resolver = "2"
members = [
    "sannbox-wgpu",
    "asn-image"
]

#exclude = []
#default-members = [
#    "asn-logger",
#    "rs-core",
#    "rs-gfx-core",
#    "rs-gfx-wgpu",
#    "rs-amberskynet"
#]
