[package]
name = "ambernet-rust-engine"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = [
    # All of Bevy's official crates are within the `crates` folder!
    "crates/*",
    "modules/*", "project-web",
]

[dependencies]
asn-core = { path = "./modules/asn-core" }
asn-core-bus = { path = "./modules/asn-core-bus" }
tokio-bus = { path = "./crates/tokio-bus" }
tokio-worker-pool = { path = "./crates/tokio-worker-pool" }

[workspace.dependencies]
tokio = { version = "1.45.1", features = ["full"] }
