[package]
name = "asn_test_2d"
version = "0.1.0"
edition = "2021"

[lib]
name = "asn_test_2d"
path = "src/lib.rs"

[dependencies]
asn_render_webgl = { path="../asn_render_webgl" }
asn_core = { path = "../core" }
js-sys = "*"
[dependencies.wasm-bindgen]
version = "*"
