[package]
name = "asn-logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10"
log = "0.4"
chrono = { version = "0.4", features = ["wasmbind"] }
fern = { version = "0.6", features = ["colored"] }
