[package]
name = "asn-decoder-tiled"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
asn-core = { path = "../asn-core" }
asn-logger = { path= "../asn-logger" }
xmlparser = "0.13.5"
