[package]
name = "asn-winapi-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28.6"
asn-core = { path = "../asn-core" }
asn-logger = { path = "../asn-logger" }
wgpu = { version = "0.16" }
