[package]
name = "rs-gfx-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.2"
wgpu = "0.14"
winit = "0.27"
rs-core = { path = "../rs-core" }
rs-core-gfx = { path = "../rs-core-gfx" }

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
