[package]
name = "rs-gfx-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.3"
wgpu = "0.16"
winit = "0.28"
rs-core = { path = "../rs-core" }
rs-gfx-core = { path = "../rs-gfx-core" }

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
