[package]
name = "sannbox-wgpu"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "sannbox-wgpu"
path = "src/main.rs"

[dependencies]
asn-logger = { path = "../asn-logger" }
asn-core = { path = "../asn-core" }
asn-image = { path = "../asn-image" }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
bytemuck = { version = "1.13.1", features = [ "derive" ] }
wgpu = { version = "0.17.0" }
winit = "0.28.6"
pollster = "0.3.0"
[dependencies.image]
version = "0.24.7"
default-features = false
features = ["png", "jpeg"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "0.17.0", features = ["webgl"]}
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = [
    "Document",
    "Window",
    "Element",
]}
