[package]
name = "project-web"
version = "0.1.0"
edition = "2024"

[features]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
asn-logger = { git = "https://github.com/amberskynet/asn-logger.git", tag = "1.0.0", features = [] }

[dev-dependencies]
wasm-bindgen-test = "0.3.50"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
