[package]
name = "asn-wgpu-released"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
asn-core = { path = "../../../asn-core" }
asn-winapi-traits = { path = "../../../asn-winapi-traits" }
asn-logger = { path = "../../../asn-logger" }
pollster = "0.4.0"
winit = "0.30.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { version = "24.0.1" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "24.0.1", default-features = false, features = [
    "wgsl",
    "dx12",
    "metal",
    "webgpu",
    "webgl"
] }
