[package]
name = "amberskynet"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "*"
uuid = { version="*", features = ['wasm-bindgen', 'v4'] }
js-sys = "*"

[dependencies.wasm-bindgen]
version = "*"

[dependencies.web-sys]
version = "*"
features = [
    "Window",
    'Document',
    'Element',
    'HtmlCanvasElement',
    'WebGlRenderingContext',
    'WebGlProgram',
    'WebGlShader',
    'WebGlBuffer',
    'WebGlUniformLocation'
]
