[workspace]

members = [
    "amberskynet",
    "amberskynet_logger_web",
    "asn_render_webgl",
    "asn_math",
    "asn_test_2d",
    "asn_view_2d",
    "asn_render_color_quad",
    "./renders/test_triangle"
]
