[package]
name = "asn_view_2d"
version = "0.1.0"
edition = "2021"

[lib]
name = "asn_view_2d"
path = "src/lib.rs"

[dependencies]
asn_render_webgl = { path="../asn_render_webgl" }
amberskynet_logger_web = { path="../amberskynet_logger_web" }
asn_core = { path = "../core" }
